## ---------------------------------------------------------------------
##
## Copyright (C) 2017 by the gscf authors
##
## This file is part of gscf.
##
## gscf is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published
## by the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## gscf is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with gscf. If not, see <http://www.gnu.org/licenses/>.
##
## ---------------------------------------------------------------------

language: cpp
sudo: required
dist: trusty

branches:
  except:
    - dev
    - /^dev-.*$/
    - /^dev_.*$/

env:
  global:
    # Use two threads in parallel
    - CORES=2
    #
    # Use a known-to-work rapidcheck seed
    #- RC_PARAMS="seed=16920708173099178154 verbose_progress=1 noshrink=1"
    #
    # The regex for tests to run (disable running tests by TESTS=0)
    - TESTS=1  TESTS_REGEX="gscf_tests_"

before_install:
    - travis_retry pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test     # libstdc++-4.9-dev (gcc 4.8's libstdc++ is buggy)
      - llvm-toolchain-trusty-3.9   # clang-3.9
    packages:
      - ninja-build
      #
      # Packages for linalgwrap
      - libarmadillo-dev
      - libboost-dev
      - liblapack-dev
      - libblas-dev

matrix:
  include:
    # Clang 3.5 with disabled c++14 support
    - install:
      - travis_retry sudo apt-get install -y libstdc++-4.9-dev
      - export EXTRA_OPTS="-DDRB_MAXIMUM_CXX_STANDARD=11"
      - export GCOV="llvm-cov gcov"
      compiler: clang
      env: CC_COMP="clang" CXX_COMP="clang++"
    #
    # Clang 3.9 (has c++14)
    - install:
      - travis_retry sudo apt-get install -y clang-3.9 libstdc++-4.9-dev
      - export GCOV="llvm-cov-3.9 gcov"
      compiler: clang
      env: CC_COMP="clang-3.9" CXX_COMP="clang++-3.9"
    #
    # gcc-4.8 (c++11 and without tests, since rapidcheck does not compile like this)
    - install:
      - export TESTS=0 EXTRA_OPTS="-DGSCF_ENABLE_TESTS=OFF"
      compiler: gcc
      env: CC_COMP="gcc" CXX_COMP="g++"
    #
    # gcc-5 (with tests and c++14)
    - install:
      - travis_retry sudo apt-get install -y g++-5
      - export GCOV="gcov-5"
      compiler: gcc
      env: CC_COMP="gcc-5" CXX_COMP="g++-5"
    #
    # Clang-tidy 3.9
    - install:
      - travis_retry sudo apt-get install -y clang-3.9 libstdc++-4.9-dev clang-tidy-3.9
      # Install yaml for the python scripts generated by SetupClangTargets.cmake
      - travis_retry pip3 install --user pyyaml
      - export BUILD_TARGET="clang-tidy-gscf"
      - export TESTS=0
      compiler: clang
      env: CC_COMP="clang-3.9" CXX_COMP="clang++-3.9" BUILD_TARGET="clang-tidy-gscf"

script:
  - cmake --version
  - ninja --version
  - mkdir ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_CXX_COMPILER=${CXX_COMP} -DCMAKE_C_COMPILER=${CC_COMP}
           -DCMAKE_BUILD_TYPE=DebugRelease ${EXTRA_OPTS}
           -DDRB_COVERAGE_Debug=ON
           -DAUTOCHECKOUT_MISSING_REPOS=ON
           -DRC_ENABLE_TESTS=OFF
           -DKRIMS_ENABLE_TESTS=OFF -DKRIMS_ENABLE_EXAMPLES=OFF
           -DLINALGWRAP_ENABLE_TESTS=OFF -DLINALGWRAP_ENABLE_EXAMPLES=OFF
           -GNinja ..
  - cmake --build  . --target ${BUILD_TARGET:-all} -- -j ${CORES}
  - if [ "${TESTS}" != "0" ]; then
        ctest -j ${CORES} --output-on-failure -R "${TESTS_REGEX}"
    ;else true; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ "${GCOV}" ]; then coveralls --gcov "$GCOV" --gcov-options '\-lp'
           --root ${PWD} --build-root ${PWD}/build
           --include src/gscf
    ;fi
