## ---------------------------------------------------------------------
## Put licence text here
## ---------------------------------------------------------------------

## DO NOT EDIT
## This file is automatically generated from a file in the repository "krims".
## Edit the original and call the script "update_from_sister_repos.sh" instead.

# Finds and sets up rapidcheck under the target name stored in the variable
#     rapidcheck_TARGET
# such that just linking against it as a dependency does everything
# automatically.
#
# In case the rapidcheck library is not found and AUTOCHECKOUT_MISSING_LIBS is
# set to ON, rapidcheck is automatically checked out into the external
# subdirectory and configured for building.
#
# Otherwise a fatal error is produced.
#

#
# Options and properties required
#
option(AUTOCHECKOUT_MISSING_REPOS "Automatically checkout missing repositories" OFF)

#
# -------
#

set(rapidcheck_TARGET "rapidcheck")
if (TARGET "${rapidcheck_TARGET}")
	message(STATUS "Found target rapidcheck, assume rapidcheck already configured for build.")
	return()
endif()

# Try to find rapidcheck somewhere
find_package(rapidcheck QUIET CONFIG)
string(TOUPPER "${PROJECT_NAME}" PROJECT_UPPER)
if ("${rapidcheck_DIR}" STREQUAL "rapidcheck_DIR-NOTFOUND")
	if (AUTOCHECKOUT_MISSING_REPOS)
		execute_process(
			COMMAND "sh" "get_rapidcheck.sh"
			WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}/external"
			RESULT_VARIABLE RES
		)
		if (NOT RES EQUAL 0)
			message(FATAL_ERROR "Getting rapidcheck from git failed with error: ${RES}")
		endif()

		#
		# Proceed to configure rapidcheck
		#
		# Set option such that rapidcheck tests are built.
		set(RC_ENABLE_TESTS ON CACHE BOOL "Build RapidCheck tests")

		# Change compiler flags (CMAKE_CXX_FLAGS) to make fresh build config
		set(CMAKE_CXX_FLAGS_STORED_TMP ${CMAKE_CXX_FLAGS})
		set(CMAKE_CXX_FLAGS "")
		#enable_if_compiles(CMAKE_CXX_FLAGS "-Wno-gnu-zero-variadic-macro-arguments")

		# Add the rapidcheck subdirectory and configure its built.
		add_subdirectory(${PROJECT_SOURCE_DIR}/external/rapidcheck)

		# undo the changes to the compiler flags:
		set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS_STORED_TMP})
		unset(CMAKE_CXX_FLAGS_STORED_TMP)

		return()
	endif()

	message(FATAL_ERROR "Could not find rapidcheck library.
Either disable testing of ${PROJECT_NAME} by setting ${PROJECT_UPPER}_ENABLE_TESTS to OFF \
or enable autocheckout via -DAUTOCHECKOUT_MISSING_REPOS=ON.")
endif()

message(WARNING "This part of findRapidcheck has never been tested.")

# Add library
set(rapidcheck_TARGET "Upstream::rapidcheck")
message(STATUS "Found rapidcheck config at ${rapidcheck_CONFIG}")
